server:
  port: 8081
  
spring:
  data:
    mongodb:
      uri: mongodb+srv://stanleyvladimir:bar2005XP@cluster0.q4ibd.mongodb.net/meseroapp

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka